import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Eye } from 'lucide-react';
import type { ColumnDef, Row } from '@tanstack/react-table';
import type { SalesCreditNoteDto } from '@erp-platform/contracts';
import {
  Button,
  DataTable,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  Skeleton,
} from '@erp-platform/ui';

import { useCustomers } from '../../api/customers/queries';
import { useSalesReturns } from '../../api/sales-returns/queries';
import { useSalesCreditNote, useSalesCreditNotes } from '../../api/sales-credit-notes/queries';
import { SalesCreditNoteDetailsView } from './sales-credit-note-details-view';

/**
 * Fully read-only list — no create/edit/delete/status-transition actions anywhere in
 * this tab, matching the backend controller exactly (GET /sales-credit-notes and
 * GET /sales-credit-notes/:id only). A credit note is always auto-generated by
 * SalesReturnsService.confirm(), never a document a user drafts here.
 */
export function SalesCreditNotesTab() {
  const { t } = useTranslation();
  const { data: creditNotes, isLoading } = useSalesCreditNotes();
  const { data: customers } = useCustomers();
  const { data: salesReturns } = useSalesReturns();
  const [viewingId, setViewingId] = useState<string | null>(null);

  const { data: viewingCreditNote, isLoading: viewingLoading } = useSalesCreditNote(viewingId);

  const customerById = useMemo(() => new Map((customers ?? []).map((c) => [c.id, c])), [customers]);
  const salesReturnById = useMemo(
    () => new Map((salesReturns ?? []).map((r) => [r.id, r])),
    [salesReturns],
  );

  const columns = useMemo<ColumnDef<SalesCreditNoteDto>[]>(
    () => [
      { accessorKey: 'creditNoteNumber', header: t('sales.salesCreditNotes.creditNoteNumber') },
      {
        id: 'customer',
        header: t('sales.salesCreditNotes.customer'),
        accessorFn: (row: SalesCreditNoteDto) => customerById.get(row.customerId)?.name ?? '—',
      },
      {
        id: 'salesReturn',
        header: t('sales.salesCreditNotes.salesReturn'),
        accessorFn: (row: SalesCreditNoteDto) =>
          salesReturnById.get(row.salesReturnId)?.returnNumber ?? '—',
      },
      {
        id: 'createdAt',
        header: t('sales.salesCreditNotes.createdAt'),
        accessorFn: (row: SalesCreditNoteDto) =>
          new Date(row.createdAt).toLocaleDateString('ar-EG'),
      },
      {
        id: 'actions',
        header: '',
        cell: ({ row }: { row: Row<SalesCreditNoteDto> }) => (
          <Button variant="ghost" size="icon" onClick={() => setViewingId(row.original.id)}>
            <Eye className="h-4 w-4" />
          </Button>
        ),
      },
    ],
    [t, customerById, salesReturnById],
  );

  return (
    <div className="grid gap-4">
      <div className="flex flex-wrap items-center justify-end gap-2"></div>

      <DataTable columns={columns} data={creditNotes ?? []} isLoading={isLoading} />

      <Dialog open={viewingId !== null} onOpenChange={(open) => !open && setViewingId(null)}>
        <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-3xl">
          <DialogHeader>
            <DialogTitle>{t('sales.salesCreditNotes.viewDetails')}</DialogTitle>
          </DialogHeader>
          {viewingLoading ? <Skeleton className="h-40 w-full" /> : null}
          {viewingCreditNote ? <SalesCreditNoteDetailsView creditNote={viewingCreditNote} /> : null}
        </DialogContent>
      </Dialog>
    </div>
  );
}
