import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import type { SalesCreditNoteWithLinesDto } from '@erp-platform/contracts';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@erp-platform/ui';

import { useCustomers } from '../../api/customers/queries';
import { useSalesReturns } from '../../api/sales-returns/queries';
import { useVariantIndex } from '../../hooks/sales-credit-notes/use-variant-index';
import { formatMoney } from '../../../../lib/money';
import { LineTaxesNote } from '../../../../components/taxes/line-taxes-note';
import { QuantityWithUnit } from '../../../../components/product/unit-select';

/**
 * Read-only header + lines + total — same shape as every other Sales details view
 * (Quotations, Sales Invoices), but with no status badge and no action buttons: a
 * credit note has no lifecycle (see migration 0053's class comment — it's a one-way
 * financial fact, always auto-generated by SalesReturnsService.confirm(), never
 * created/edited by a user). totalAmount is server-computed on every GET, rendered
 * as-is rather than summed client-side, matching every other Money-carrying entity.
 */
export function SalesCreditNoteDetailsView({ creditNote }: { creditNote: SalesCreditNoteWithLinesDto }) {
  const { t } = useTranslation();
  const { data: customers } = useCustomers();
  const { data: salesReturns } = useSalesReturns();
  const variantIndex = useVariantIndex();

  const customerById = useMemo(() => new Map((customers ?? []).map((c) => [c.id, c])), [customers]);
  const salesReturnById = useMemo(() => new Map((salesReturns ?? []).map((r) => [r.id, r])), [salesReturns]);

  return (
    <div className="grid gap-3">
      <div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
        <div>
          <p className="text-muted-foreground">{t('sales.salesCreditNotes.creditNoteNumber')}</p>
          <p className="font-medium">{creditNote.creditNoteNumber}</p>
        </div>
        <div>
          <p className="text-muted-foreground">{t('sales.salesCreditNotes.customer')}</p>
          <p className="font-medium">{customerById.get(creditNote.customerId)?.name ?? '—'}</p>
        </div>
        <div>
          <p className="text-muted-foreground">{t('sales.salesCreditNotes.salesReturn')}</p>
          <p className="font-medium">{salesReturnById.get(creditNote.salesReturnId)?.returnNumber ?? '—'}</p>
        </div>
        {creditNote.vatAmount.amountMinorUnits !== '0' ? (
          <div>
            <p className="text-muted-foreground">{t('taxes.totals.vat')}</p>
            <p className="font-medium">
              {formatMoney(creditNote.vatAmount.amountMinorUnits, creditNote.vatAmount.currency)}
            </p>
          </div>
        ) : null}
        <div>
          <p className="text-muted-foreground">{t('sales.salesCreditNotes.totalAmount')}</p>
          <p className="font-medium">
            {formatMoney(creditNote.totalAmount.amountMinorUnits, creditNote.totalAmount.currency)}
          </p>
        </div>
        <div className="col-span-2 sm:col-span-3">
          <p className="text-muted-foreground">{t('sales.salesCreditNotes.notes')}</p>
          <p className="font-medium">{creditNote.notes ?? '—'}</p>
        </div>
      </div>

      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>{t('sales.salesCreditNotes.lineProduct')}</TableHead>
            <TableHead>{t('sales.salesCreditNotes.lineQuantity')}</TableHead>
            <TableHead>{t('sales.salesCreditNotes.lineUnitPriceHeader')}</TableHead>
            <TableHead>{t('documents.lineTotal')}</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {creditNote.lines.map((line) => (
            <TableRow key={line.id}>
              <TableCell>
                {variantIndex.get(line.productVariantId)?.productName ?? '—'} (
                {variantIndex.get(line.productVariantId)?.sku ?? '—'})
              </TableCell>
              <TableCell>
                <QuantityWithUnit
                  quantity={line.quantity}
                  productVariantId={line.productVariantId}
                  unitOfMeasureId={line.unitOfMeasureId}
                />
              </TableCell>
              <TableCell>{formatMoney(line.unitPrice.amountMinorUnits, line.unitPrice.currency)}</TableCell>
              <TableCell>
                {formatMoney(line.netAmount.amountMinorUnits, line.netAmount.currency)}
                <LineTaxesNote taxes={line.taxes} />
              </TableCell>
            </TableRow>
          ))}
          {creditNote.lines.length === 0 ? (
            <TableRow>
              <TableCell colSpan={4} className="py-6 text-center text-muted-foreground">
                {t('common.noResults')}
              </TableCell>
            </TableRow>
          ) : null}
        </TableBody>
      </Table>
    </div>
  );
}
