import { Money } from '@erp-platform/shared-kernel';

/**
 * Sales Credit Note (master doc §10, step 4 — Sales; the financial
 * credit-note mechanism deferred by migration 0047, built per the
 * user's explicit approval). See migration 0053's class comment for
 * the full reasoning — always auto-generated by
 * SalesReturnsService.confirm(), never user-created; no status
 * lifecycle (it IS the one-way-door fact, not a draft of one).
 */
export interface SalesCreditNoteLine {
  id: string;
  salesCreditNoteId: string;
  salesReturnLineId: string;
  productVariantId: string;
  quantity: number;
  unitPrice: Money;
  createdAt: Date;
  /** Unit the line is in (null = product base unit) and base units per 1 of it — migration 0079. */
  unitOfMeasureId: string | null;
  unitFactor: number;
}

export interface SalesCreditNote {
  id: string;
  creditNoteNumber: string;
  salesReturnId: string;
  customerId: string;
  currency: string;
  notes: string | null;
  customFields: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

export interface SalesCreditNoteWithLines extends SalesCreditNote {
  lines: SalesCreditNoteLine[];
  /** Derived, never stored — same "never store what's derivable" precedent as every other document total in this module. */
  totalAmount: Money;
}

/** productVariantId/unitPrice are always derived server-side (see SalesCreditNotesService), never taken from a caller — this entity has no public create endpoint at all. */
export interface CreateSalesCreditNoteLineInput {
  salesReturnLineId: string;
  productVariantId: string;
  quantity: number;
  unitPrice: Money;
  /** Line unit (migration 0079); omitted = base unit, factor 1. */
  unitOfMeasureId?: string | null;
  unitFactor?: number;
}

export interface CreateSalesCreditNoteInput {
  salesReturnId: string;
  customerId: string;
  currency: string;
  lines: CreateSalesCreditNoteLineInput[];
  notes?: string | null;
}

export function calculateSalesCreditNoteTotal(lines: { unitPrice: Money; quantity: number }[]): Money {
  if (lines.length === 0) {
    throw new Error('Cannot compute a sales credit note total with zero lines.');
  }
  return lines.reduce(
    (total, line) => total.add(line.unitPrice.multiplyByQuantity(line.quantity)),
    Money.zero(lines[0].unitPrice.currency),
  );
}
