import { Controller, Get, Param, Post, Query, UseGuards } from '@nestjs/common';
import { accountingPeriodSchema, type AccountingPeriodDto } from '@erp-platform/contracts';
import { TenantConnectionManager } from '../../../shared/tenancy/tenant-connection-manager';
import { CurrentTenantSchema } from '../../../shared/auth/current-tenant-schema.decorator';
import { CurrentUser } from '../../../shared/auth/current-user.decorator';
import type { JwtAccessPayload } from '../../../shared/auth/jwt-payload.type';
import { JwtAuthGuard } from '../../../shared/auth/jwt-auth.guard';
import { PermissionsGuard } from '../../../shared/auth/permissions.guard';
import { RequirePermissions } from '../../../shared/auth/require-permissions.decorator';
import { AccountingPeriodsService } from '../application/services/accounting-periods.service';
import { AccountingEventPublisher } from '../infrastructure/events/accounting-event-publisher';

/**
 * No PlanFeatureGuard yet — see ChartOfAccountsController's class
 * comment. No POST/DELETE for a single period — the whole set for a
 * fiscal year is generated by FiscalYearsService.create(); this
 * controller only lists and toggles open/closed.
 */
@UseGuards(JwtAuthGuard, PermissionsGuard)
@RequirePermissions('accounting.manage')
@Controller('accounting-periods')
export class AccountingPeriodsController {
  constructor(
    private readonly service: AccountingPeriodsService,
    private readonly connections: TenantConnectionManager,
    private readonly events: AccountingEventPublisher,
  ) {}

  @Get()
  async list(
    @CurrentTenantSchema() schema: string,
    @Query('fiscalYearId') fiscalYearId?: string,
  ): Promise<AccountingPeriodDto[]> {
    const db = this.connections.getClient(schema);
    const periods = await this.service.list(db, fiscalYearId);
    return periods.map((p) => accountingPeriodSchema.parse(p));
  }

  @Get(':id')
  async getById(@CurrentTenantSchema() schema: string, @Param('id') id: string): Promise<AccountingPeriodDto> {
    const db = this.connections.getClient(schema);
    const period = await this.service.getById(db, id);
    return accountingPeriodSchema.parse(period);
  }

  @Post(':id/close')
  async close(
    @CurrentTenantSchema() schema: string,
    @CurrentUser() user: JwtAccessPayload,
    @Param('id') id: string,
  ): Promise<AccountingPeriodDto> {
    const db = this.connections.getClient(schema);
    const period = await this.service.close(db, id);
    this.events.publish('accounting_period', 'closed', { schema, entityId: period.id, actorUserId: user.sub });
    return accountingPeriodSchema.parse(period);
  }

  @Post(':id/reopen')
  async reopen(
    @CurrentTenantSchema() schema: string,
    @CurrentUser() user: JwtAccessPayload,
    @Param('id') id: string,
  ): Promise<AccountingPeriodDto> {
    const db = this.connections.getClient(schema);
    const period = await this.service.reopen(db, id);
    this.events.publish('accounting_period', 'reopened', { schema, entityId: period.id, actorUserId: user.sub });
    return accountingPeriodSchema.parse(period);
  }
}
