import { z } from 'zod';
import { moneySchema } from '../inventory/money.contract';
import { documentTotalsSchema, lineTaxSchema } from '../settings/tax-rule.contract';

/**
 * Sales Credit Note DTOs (CLAUDE.md §10, step 4 — Sales). Read-only from
 * the API's point of view — there is no createSalesCreditNoteSchema:
 * a credit note is always auto-generated by SalesReturnsService.confirm(),
 * never accepted as user input. See migration 0053's class comment.
 */
export const salesCreditNoteLineSchema = z.object({
  id: z.string().uuid(),
  salesCreditNoteId: z.string().uuid(),
  salesReturnLineId: z.string().uuid(),
  productVariantId: z.string().uuid(),
  unitOfMeasureId: z.string().uuid().nullable().default(null),
  unitFactor: z.number().positive().default(1),
  quantity: z.number().positive(),
  unitPrice: moneySchema,
  netAmount: moneySchema,
  taxes: z.array(lineTaxSchema),
  createdAt: z.coerce.date(),
});
export type SalesCreditNoteLineDto = z.infer<typeof salesCreditNoteLineSchema>;

export const salesCreditNoteSchema = z.object({
  id: z.string().uuid(),
  creditNoteNumber: z.string().min(1),
  salesReturnId: z.string().uuid(),
  customerId: z.string().uuid(),
  currency: z.string().regex(/^[A-Z]{3}$/, 'currency must be a three-letter ISO 4217 code'),
  notes: z.string().nullable(),
  customFields: z.record(z.unknown()),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type SalesCreditNoteDto = z.infer<typeof salesCreditNoteSchema>;

export const salesCreditNoteWithLinesSchema = salesCreditNoteSchema.extend({
  lines: z.array(salesCreditNoteLineSchema),
  ...documentTotalsSchema.shape,
});
export type SalesCreditNoteWithLinesDto = z.infer<typeof salesCreditNoteWithLinesSchema>;
