import { lazy } from 'react';
import { Navigate, Outlet, type RouteObject } from 'react-router-dom';

const PartyStatementPage = lazy(() =>
  import('../statements').then((m) => ({ default: m.PartyStatementPage })),
);
const PartyBalancesPage = lazy(() =>
  import('../statements').then((m) => ({ default: m.PartyBalancesPage })),
);

const CustomersPage = lazy(() => import('./components/customers').then((m) => ({ default: m.CustomersPage })));
const QuotationsPage = lazy(() => import('./components/quotations').then((m) => ({ default: m.QuotationsPage })));
const SalesOrdersPage = lazy(() =>
  import('./components/sales-orders').then((m) => ({ default: m.SalesOrdersPage })),
);
const DeliveriesPage = lazy(() => import('./components/deliveries').then((m) => ({ default: m.DeliveriesPage })));
const SalesInvoicesPage = lazy(() =>
  import('./components/sales-invoices').then((m) => ({ default: m.SalesInvoicesPage })),
);
const SalesInvoiceCreatePage = lazy(() =>
  import('./components/sales-invoices').then((m) => ({ default: m.SalesInvoiceCreatePage })),
);
const SalesInvoiceDetailsPage = lazy(() =>
  import('./components/sales-invoices').then((m) => ({ default: m.SalesInvoiceDetailsPage })),
);
const PaymentsReceivedPage = lazy(() =>
  import('./components/payments-received').then((m) => ({ default: m.PaymentsReceivedPage })),
);
const SalesReturnsPage = lazy(() =>
  import('./components/sales-returns').then((m) => ({ default: m.SalesReturnsPage })),
);
const EtaCredentialsPage = lazy(() =>
  import('./components/eta-credentials').then((m) => ({ default: m.EtaCredentialsPage })),
);
const SalesCreditNotesPage = lazy(() =>
  import('./components/sales-credit-notes').then((m) => ({ default: m.SalesCreditNotesPage })),
);
const PosPage = lazy(() => import('./components/pos').then((m) => ({ default: m.PosPage })));

/**
 * Routes owned by the Sales module. Follows the same route-per-entity, lazy-loaded
 * structure as Inventory/Purchases (see purchases/routes.tsx) — router.tsx just spreads
 * this array, and AppShell's single <Suspense> around <Outlet /> covers these lazy
 * routes too.
 *
 * All 8 backend entities (Customers, Quotations, Sales Orders, Deliveries, Sales
 * Invoices, Payments Received, Sales Returns, Sales Credit Notes) plus the ETA
 * credentials settings screen (config storage only — the ETA submission engine itself
 * is out of scope, see that page's own doc comment). Sales Credit Notes is read-only —
 * always auto-generated by SalesReturnsService.confirm(), never created here — so its
 * page is a plain list/detail view with no create action.
 */
export const salesRoutes: RouteObject[] = [
  {
    path: 'sales',
    // No UI of its own — groups the sub-section routes under '/sales'.
    element: <Outlet />,
    children: [
      { index: true, element: <Navigate to="customers" replace /> },
      { path: 'customers', element: <CustomersPage /> },
      { path: 'customers/:id/statement', element: <PartyStatementPage kind="customer" /> },
      { path: 'receivables', element: <PartyBalancesPage kind="customer" /> },
      { path: 'quotations', element: <QuotationsPage /> },
      { path: 'sales-orders', element: <SalesOrdersPage /> },
      { path: 'deliveries', element: <DeliveriesPage /> },
      { path: 'sales-invoices', element: <SalesInvoicesPage /> },
      { path: 'sales-invoices/new', element: <SalesInvoiceCreatePage /> },
      { path: 'sales-invoices/:id', element: <SalesInvoiceDetailsPage /> },
      { path: 'payments-received', element: <PaymentsReceivedPage /> },
      { path: 'sales-returns', element: <SalesReturnsPage /> },
      { path: 'sales-credit-notes', element: <SalesCreditNotesPage /> },
      { path: 'eta-credentials', element: <EtaCredentialsPage /> },
    ],
  },
  // POS (Stage 4) is a standalone top-level screen, not a Sales sub-tab — a sibling
  // route here rather than a child of the 'sales' group above, per its own standalone
  // sidebar item (see nav-items.ts).
  { path: 'pos', element: <PosPage /> },
];
