import { Controller, Get, Param, Query, UseGuards } from '@nestjs/common';
import {
  salesCreditNoteSchema,
  salesCreditNoteWithLinesSchema,
  type SalesCreditNoteDto,
  type SalesCreditNoteWithLinesDto,
} from '@erp-platform/contracts';
import type { SalesCreditNote, SalesCreditNoteWithLines } from '../domain/sales-credit-note.entity';
import { TenantConnectionManager } from '../../../shared/tenancy/tenant-connection-manager';
import { CurrentTenantSchema } from '../../../shared/auth/current-tenant-schema.decorator';
import { JwtAuthGuard } from '../../../shared/auth/jwt-auth.guard';
import { PermissionsGuard } from '../../../shared/auth/permissions.guard';
import { RequirePermissions } from '../../../shared/auth/require-permissions.decorator';
import { SalesCreditNotesService } from '../application/services/sales-credit-notes.service';
import { moneyToDto } from './money.mapper';

function creditNoteToDto(creditNote: SalesCreditNote): SalesCreditNoteDto {
  return salesCreditNoteSchema.parse(creditNote);
}

function creditNoteWithLinesToDto(creditNote: SalesCreditNoteWithLines): SalesCreditNoteWithLinesDto {
  return salesCreditNoteWithLinesSchema.parse({
    ...creditNote,
    lines: creditNote.lines.map((line) => ({ ...line, unitPrice: moneyToDto(line.unitPrice) })),
    totalAmount: moneyToDto(creditNote.totalAmount),
  });
}

/**
 * Read-only — a credit note is always auto-generated by
 * SalesReturnsService.confirm(), never created/edited/deleted through
 * this controller (no @Post/@Patch/@Delete at all — see migration
 * 0053's class comment). No PlanFeatureGuard yet — same deliberate,
 * tracked gap as the rest of this module.
 */
@UseGuards(JwtAuthGuard, PermissionsGuard)
@RequirePermissions('sales.manage')
@Controller('sales-credit-notes')
export class SalesCreditNotesController {
  constructor(
    private readonly service: SalesCreditNotesService,
    private readonly connections: TenantConnectionManager,
  ) {}

  @Get()
  async list(
    @CurrentTenantSchema() schema: string,
    @Query('salesReturnId') salesReturnId?: string,
  ): Promise<SalesCreditNoteDto[]> {
    const db = this.connections.getClient(schema);
    if (salesReturnId) {
      const creditNote = await this.service.findBySalesReturnId(db, salesReturnId);
      return creditNote ? [creditNoteToDto(creditNote)] : [];
    }
    const creditNotes = await this.service.list(db);
    return creditNotes.map(creditNoteToDto);
  }

  @Get(':id')
  async getById(
    @CurrentTenantSchema() schema: string,
    @Param('id') id: string,
  ): Promise<SalesCreditNoteWithLinesDto> {
    const db = this.connections.getClient(schema);
    const creditNote = await this.service.getById(db, id);
    return creditNoteWithLinesToDto(creditNote);
  }
}
